#!/bin/bash

make -f /opt/src/workflows/recog/Makefile $1 \
  namespace=recog/mnist \
  dataset=mnist \
  input_shape="1 28 28" \
  model_name=mini \
  batch_size=64 \
  val_batch_size=256 \
  samples_per_epoch=-1 \
  val_samples_per_epoch=-1 \
  epochs=10 \
  nsamples=-1 \
  max_plots=20 \
  log_interval=10
